version: '3'
services:
  express:
    build: ./backend/
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    command: node app.js
  db:
    build: ./backend/docker-db
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autorent
  #TODO:
  #phpmyadmin:
  #  image: php:7.4-fpm-alpine
  #  container_name: phpmyadmin
  #  restart: always
  #  ports:
  #   - 8080:80

  #TODO: build frontend Expo with Docker